title: "Tato Khundadze"
name: "Tato Khundadze"
description: >-
  PhD candidate in Economics at The New School, specializing in machine learning applications to macroeconomic modeling and economic dynamics.

url: "https://titekhund.github.io"
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Author details
author:
  name     : "Tato Khundadze"
  avatar   : "/assets/images/profile.jpg" # replace this with your uploaded photo
  bio      : "PhD candidate in Economics | Machine Learning | Macroeconomics"
  location : "New York, NY"
  email    : "your.email@example.com"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.email@example.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/titekhund"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/tato-khundadze-7b8732145"

# Social media previews
twitter_username: tato_khundadze
github_username:  titekhund

# Pagination
paginate: 5
paginate_path: /page:num/

# Enable profile sidebar
show_excerpts: true
minimal_mistakes_skin: "default"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

# About Me
about_me: >-
  I am a PhD candidate in Economics at The New School for Social Research, specializing in machine learning applications to macroeconomic modeling and economic dynamics. My research integrates deep reinforcement learning, scientific machine learning, and statistical inference to better understand economic fluctuations and inform policy design.

  I have experience teaching econometrics and machine learning to both undergraduate and graduate students, and I have contributed to international research and consulting projects with institutions such as the UNDP and the Centre for Economic Policy. My work is grounded in both theoretical rigor and practical application, with a strong interest in data-driven approaches to public policy and macroeconomic forecasting.

  Technically, I am proficient in Python, Stata, and LaTeX, and I enjoy developing models that translate economic insight into actionable policy recommendations. I am especially interested in interdisciplinary collaborations at the intersection of economics, data science, and public policy.

include:
  - _pages
