title: "Tato Khundadze"
name: "Tato Khundadze"
description: >-
  PhD candidate in Economics at The New School. Specializing in machine learning for macroeconomic modeling and economic dynamics.
url: "https://titekhund.github.io"
